name: Node Github CI

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: SSH Execute Commands
              uses: JimCronqvist/action-ssh@1.0.0
              with:
                  hosts: ${{ secrets.SSH_HOST }}
                  privateKey: ${{ secrets.SSH_KEY }}
                  command: |
                      cd ~/redlink2web
                      git pull
                      yarn install
                      yarn build
                      pm2 delete nostalgia
                      pm2 start --watch --name 'nostalgia' ecosystem.config.js